version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root$IX66
      MYSQL_DATABASE: mtg_collection_tracker_db
    networks:
      - app-network
    deploy:
      placement:
        constraints: [node.role == manager]

  spring-boot-app:
    image: timmonsevan/timmons-ceg3120:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root$IX66
    depends_on:
      - mysql
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

networks:
  app-network:
    driver: overlay