version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root$IX66
      MYSQL_DATABASE: mtg_collection_tracker_db
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mtg_collection_tracker_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root$IX66