name: CI

on:
  workflow_dispatch:
  push:
    tags: 
      - "*"
env:
  TAG_NAME: ${{ github.event.release.tag_name }}
  
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: |
          name=${{ secrets.DOCKER_USERNAME }}/timmons-ceg3120
        tags: |
          type=semver,pattern={{major}},value=${{ env.TAG_NAME }}
          type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG_NAME }}
    
    - name: build container with latest, major and major.minor tags
      uses: docker/build-push-action@v6.15.0
      with: 
        file: ./demo/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}, ${{ secrets.DOCKER_USERNAME }}/timmons-ceg3120:latest

    - name: Setup SSH key
      uses: volodymyr-borodin/setup-ssh-key@v1
      with:
        # Private key required to access the host
        private-key: ${{ secrets.MYAPP_KEY }}
        # Hostname or IP to add to the known hosts file
        known-hosts: ${{ variables.MYAPP_IP }}

    - name: Run deploy script on remote server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ variables.MYAPP_IP }} \
        'bash -s' < ./deployment/deploy.sh MtgCollectionApp
