
name: CI

on: 
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: 
      - "main"
    tags: 
      - 'v*'
  
  workflow_dispatch:

jobs:
  # build the latest tagged container
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v4
    # login to Docker
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/timmons-ceg3120
        tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}]
            type=semver,pattern={{major}}.{{minor}}
    
    # build the container and push to docker hub
    - name: build container with latest, major and major.minor tags
      uses: docker/build-push-action@v6.15.0
      with: 
        file: ./demo/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
