
name: CI

on: 
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags: 
      - 'v*'
env:
  TAG_NAME: ${{ github.event.release.tag_name }}
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/timmons-ceg3120
        tags: |
          type=semver,pattern={{major}},value=${{ env.TAG_NAME }}
          type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG_NAME }}
    
    - name: build container with latest, major and major.minor tags
      uses: docker/build-push-action@v6.15.0
      with: 
        context: .
        file: ./demo/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/timmons-ceg3120:${{ steps.meta.outputs.tags }}, ${{ secrets.DOCKER_USERNAME }}/timmons-ceg3120:latest
